// handmodified

$.event.props.push('dataTransfer');

var dragover = $('.drag-bin').on('dragover', function () { return false; } );

var drag = $(document).asEventStream('dragstart', '.item')
  .doAction(function (e) {
    e.dataTransfer.effectAllowed = 'move';
    return e.dataTransfer.setData('tmp', '');
  })
  .toProperty();

var drop = $('.drag-bin').asEventStream('drop')
  .filter(function (it) { return it.type === 'drop'; })
  .toProperty();

Bacon.combineAsArray(drag, drop)
  .filter  (function (arg) { return arg[0].timeStamp < arg[1].timeStamp; })
  .map     (function (arg) { return {item: arg[0].target, dest: arg[1].target}; })
  .filter  (function (arg) { return arg.item.dataset.type === arg.dest.dataset.type
                               || arg.dest.dataset.type === null; })
  .doAction(function (arg) { arg.dest.appendChild(arg.item); });

$('.item .remove').asEventStream('click').assign(function (e) {
    $('#home-bin').append( $(e.target).closest('.item') );
});

//// original (Generated by LiveScript 1.5.0)

//var homeBin, drag, drop, this$ = this;
//$.event.props.push('dataTransfer');
//homeBin = $('#home-bin');
//drag = $(document).asEventStream('dragstart', '.item').doAction(function (e) {
//    e.dataTransfer.effectAllowed = 'move';
//    return e.dataTransfer.setData('tmp', '');
//}).toProperty();
//drop = $('.drag-bin').asEventStream('dragover drop').doAction(function (it) {
//    return it.preventDefault();
//}).filter(function (it) {
//    return it.type === 'drop';
//}).toProperty();
//drag.combine(drop, function (a, b) {
//    return [a, b];
//}).filter(function (arg$) {
//    var a, b;
//    a = arg$[0], b = arg$[1];
//    return a.timeStamp < b.timeStamp;
//}).map(function (arg$) {
//    var a, b;
//    a = arg$[0], b = arg$[1];
//    return {
//        item: a.target,
//        dest: b.target
//    };
//}).filter(function (arg$) {
//    var item, dest;
//    item = arg$.item, dest = arg$.dest;
//    return item.dataset.type === dest.dataset.type || dest.dataset.type == null;
//}).assign(function (arg$) {
//    var item, dest;
//    item = arg$.item, dest = arg$.dest;
//    dest.appendChild(
//        item);
//});
//$('.item .remove').asEventStream('click').assign(function (e) {
//    homeBin.append(
//        $(e.target).closest('.item'));
//});

