// Generated by LiveScript 1.5.0

    var homeBin, drag, drop, this$ = this;
    $.event.props.push('dataTransfer');
    homeBin = $('#home-bin');
    drag = $(document).asEventStream('dragstart', '.item').doAction(function(e){
        e.dataTransfer.effectAllowed = 'move';
        return e.dataTransfer.setData('tmp', '');
    }).toProperty();
    drop = $('.drag-bin').asEventStream('dragover drop').doAction(function(it){
        return it.preventDefault();
    }).filter(function(it){
        return it.type === 'drop';
    }).toProperty();
    drag.combine(drop, function(a, b){
        return [a, b];
    }).filter(function(arg$){
        var a, b;
        a = arg$[0], b = arg$[1];
        return a.timeStamp < b.timeStamp;
    }).map(function(arg$){
        var a, b;
        a = arg$[0], b = arg$[1];
        return {
            item: a.target,
            dest: b.target
        };
    }).filter(function(arg$){
        var item, dest;
        item = arg$.item, dest = arg$.dest;
        return item.dataset.type === dest.dataset.type || dest.dataset.type == null;
    }).assign(function(arg$){
        var item, dest;
        item = arg$.item, dest = arg$.dest;
        dest.appendChild(
            item);
    });
    $('.item .remove').asEventStream('click').assign(function(e){
        homeBin.append(
            $(e.target).closest('.item'));
    });

